{
  throw new FunctorException("ExceptionPredicate invoked");
}
