{
  throw new FunctorException("ExceptionFactory invoked");
}
