{
  throw new FunctorException("ExceptionClosure invoked");
}
